### ISSUE TITLE
Releasing this to PiPy

### ISSUE THREAD

**Issue by fferegrino** [mikeckennedy/fastapi-chameleon#10]
Hi Michael; thanks for creating this. Is there a checklist you may have around to understand what would be needed to release this package into the wild? even if it is a beta version for the time being?

Also, would you need help with that? I am happy to help.

**Comment by mikeckennedy** [comment]
Hi @fferegrino I'm game to release it to PyPI. It should be pretty close. It already installs as a package and has that setup. Has a little documentation, enough I think. I just have to go through the steps to publish it.

**Comment by mikeckennedy** [comment]
Hi @fferegrino Published this to PyPI: https://pypi.org/project/fastapi-chameleon/ :)
