### ISSUE TITLE
Call to global_init() required to run any test individually

### ISSUE THREAD

**Issue by AGeekInside** [mikeckennedy/fastapi-chameleon#13]
Each specific rest requires global_init() to be ran before it can be run. The `test_can_call_init_with_good_path()` test does this, and that appears to enable all other tests to run. 

```
def test_can_call_init_with_good_path():
    fc.global_init(folder, cache_init=False)
```

If you run various tests individually, they error out because global_init is not called. I am working on a fix for the fastapi-jinja library that uses a pytest fixture to make this work. I am basically creating a fixture that is like this:

```
@pytest.fixture
def call_global_init():
    here = os.path.dirname(__file__)
    folder = os.path.join(here, "templates")
    fc.global_init(folder, cache_init=False)
```
The fixture could then be added to any test that requires global init to be called. It should work, but I want to verify.

**Comment by fferegrino** [comment]
I can pick this up, could be done even with an "auto use" fixture.

**Comment by mikeckennedy** [comment]
And thanks @AGeekInside for kicking off the issue.

**Comment by fferegrino** [comment]
I decided not to go with the auto-use fixtures; let's add the fixture for each test that needs `global_init`.

**Comment by mikeckennedy** [comment]
This is fixed with @fferegrino's latest PR I just merged. Thank you both.
