### ISSUE TITLE
returning empty dict

### ISSUE THREAD

**Issue by falkben** [mikeckennedy/fastapi-chameleon#2]
In what situation do you want to return an empty dict in this case? Seems like you'd more likely want to try to coerce to a dict and fail over to an empty dict? Though maybe you are just trying to account for `None`, in which case maybe it should be an `elif response_val is None`?

```python
try:
    model = dict(response_val)
except TypeError:
    model = {}
```

https://github.com/mikeckennedy/fastapi-chameleon/blob/4ffff6b14e5467fd802940fb32dba6b1f35d6d85/fastapi_chameleon/engine.py#L89-L90

**Comment by mikeckennedy** [comment]
Hi @falkben,

The thing I was looking to dodge was if someone returned a specialized dictionary, especially a multidict. With a normal dictionary, this is always clear: d.get('value') but I think with a multidict you *either* get a raw value or a list of values IIRC. But I decided to just allow anything that is a dictionary subclass pass through and removed that test all together. :)
